services:
  api:
    build: .
    env_file: .env
    environment:
      - RUN_MODE=api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - faiss_indices:/data/faiss_indices
    depends_on:
      db:
        condition: service_healthy

  worker:
    build: .
    command: python -c "from app.main import run_worker; run_worker()"
    env_file: .env
    environment:
      - RUN_MODE=worker
    volumes:
      - .:/app
      - faiss_indices:/data/faiss_indices
    depends_on:
      db:
        condition: service_healthy # Воркеру тоже нужна БД

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: autohh
      POSTGRES_PASSWORD: autohh
      POSTGRES_DB: autohh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autohh -d autohh"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  faiss_indices: