version: '3.8'

services:
  # ------ FRONTEND SERVICE ------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Мы обращаемся к Nginx на порт 3000
    depends_on:
      - api
    restart: always

  # ------ BACKEND API SERVICE ------
  api:
    build:
      context: ./backend
    env_file: ./backend/.env
    environment:
      - RUN_MODE=api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - faiss_indices:/data/faiss_indices
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # ------ BACKEND WORKER SERVICE ------
  worker:
    build:
      context: ./backend
    command: python -m app.services.scheduler # Измененный способ запуска
    env_file: ./backend/.env
    environment:
      - RUN_MODE=worker
    volumes:
      - ./backend:/app
      - faiss_indices:/data/faiss_indices
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # ------ DATABASE SERVICE ------
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: autohh
      POSTGRES_PASSWORD: autohh
      POSTGRES_DB: autohh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autohh -d autohh"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata:
  faiss_indices: